### ISSUE TITLE
"pkg-resources==0.0.0" error

### ISSUE THREAD

**Issue by davidsaroff** [SkalskiP/ILearnDeepLearning.py#8]
Trying to follow your "hit the ground running"

# install all required packages
pip install -r requirements.txt

produces the error

 Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 54)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 54))

taking a look at requirements.txt, line 54 in fact indicates a 0.0.0 version for pkg-resources.

**Comment by SkalskiP** [comment]
Hello. Thank you so much for bringing this bug to my attention. After doing some research I came to the conclusion that this is an error caused by Ubuntu, which gives PIP incorrect data - you can read more about it [here](https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command) and [here](https://github.com/pypa/pip/issues/4022). It seems that the correct solution in this situation is to supplement this line with `requirements.txt` - and that's what I did. If this operation causes any further errors I will reopen the issue, but in the meantime I consider the bug resolved.
